repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ '--safe' ]
  - repo: https://github.com/PyCQA/flake8
    # https://www.reddit.com/r/Python/comments/yvfww8/flake8_took_down_the_gitlab_repository_in_favor/
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [
          # E501 let black handle all line length decisions
          # W503 black conflicts with "line break before operator" rule
          # E203 black conflicts with "whitespace before ':'" rule
          '--ignore=E501,W503,E203,C901' ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        exclude: /tests/
        # --strict
        args: [--no-strict-optional, --ignore-missing-imports, --implicit-reexport]
        additional_dependencies: [
          "types-attrs",
          "types-requests"
        ]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: '.*(test|alembic|scripts).*'
          #args: [
        # Don't require docstrings for tests
        #'--match=(?!test|alembic|scripts).*\.py',
        #]